spring.application.name=jaspion
spring.datasource.url=jdbc:postgresql://localhost:5432/jaspion?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456

sprint.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

sprint.flyway.enabled=true
sprint.flyway.locations=classpath:db/migration